#!/usr/bin/env python3
"""Generate Unicode P, S, M category tables for Rust.

Run: python3 scripts/gen_unicode.py > src/tokenizer/tok_unicode.rs
"""
import sys
import unicodedata


def ranges(cats):
    lo = hi = None
    for cp in range(0x110000):
        ch = chr(cp)
        try:
            cat = unicodedata.category(ch)
        except ValueError:
            continue
        if cat and cat[0] in cats:
            if lo is None:
                lo = hi = cp
            elif cp == hi + 1:
                hi = cp
            else:
                yield lo, hi
                lo = hi = cp
    if lo is not None:
        yield lo, hi


def emit(name, it):
    rs = list(it)
    sys.stdout.write(f"pub const {name}: &[(u32, u32)] = &[\n")
    for i in range(0, len(rs), 6):
        row = ", ".join(f"(0x{a:X}, 0x{b:X})" for a, b in rs[i:i + 6])
        sys.stdout.write(f"    {row},\n")
    sys.stdout.write("];\n\n")
    return rs


print("/* GENERATED by tools/gen_unicode.py, do not edit by hand. */")
print()
l = emit("UNI_L", ranges("L"))
m = emit("UNI_N", ranges("N"))
s = emit("UNI_S", ranges("S"))

print("""#[inline]
fn uni_in(table: &[(u32, u32)], c: u32) -> bool {
    let mut lo = 0;
    let mut hi = table.len();
    while lo < hi {
        let mid = (lo + hi) / 2;
        let (a, b) = table[mid];
        if c < a {
            hi = mid;
        } else if c > b {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    false
}

#[inline]
pub fn is_l(c: u32) -> bool {
    uni_in(UNI_L, c)
}

#[inline]
pub fn is_n(c: u32) -> bool {
    uni_in(UNI_N, c)
}

#[inline]
pub fn is_s(c: u32) -> bool {
    uni_in(UNI_S, c)
}
""")