#!/usr/bin/env python3
"""Extract the ggml lookup tables used by the importance-quantization (IQ)
kernels from ``scripts/ggml-common.h`` and emit them as Rust constants.

Usage::

    python scripts/gen_iq_tables.py            # write src/kernel/iq_tables.rs
    python scripts/gen_iq_tables.py --check    # fail if the file is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

import urllib.request
import urllib.error

ggml_common_h_url = "https://raw.githubusercontent.com/ggml-org/llama.cpp/refs/heads/master/ggml/src/ggml-common.h"

try:
    req = urllib.request.Request(ggml_common_h_url, headers={"User-Agent": "python-reader"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        text = resp.read().decode("utf-8")
    print(text[:2000])
    with open(f"{ROOT}/scripts/ggml-common.h", "w", encoding="utf-8") as f:
        f.write(text)
except urllib.error.HTTPError as e:
    print("HTTPError:", e.code, e.reason)
except urllib.error.URLError as e:
    print("URLError:", e.reason)

SOURCE = ROOT / "scripts" / "ggml-common.h"
TARGET = ROOT / "src" / "kernel" / "iq_tables.rs"

# C table name -> (Rust const name, Rust element type)
TABLES = {
    "kmask_iq2xs": ("KMASK_IQ2XS", "u8"),
    "ksigns_iq2xs": ("KSIGNS_IQ2XS", "u8"),
    "ksigns64": ("KSIGNS64", "u64"),
    "kvalues_iq4nl": ("KVALUES_IQ4NL", "i8"),
    "iq1s_grid": ("IQ1S_GRID", "u64"),
    "iq2xxs_grid": ("IQ2XXS_GRID", "u64"),
    "iq2xs_grid": ("IQ2XS_GRID", "u64"),
    "iq2s_grid": ("IQ2S_GRID", "u64"),
    "iq3xxs_grid": ("IQ3XXS_GRID", "u32"),
    "iq3s_grid": ("IQ3S_GRID", "u32"),
}

BEGIN = re.compile(
    r"GGML_TABLE_BEGIN\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)"
)
END = "GGML_TABLE_END()"

HEADER = """// @generated by scripts/gen_iq_tables.py -- do not edit by hand.
//
// Lookup tables shared by the IQ (importance quantization) kernels. They are
// extracted verbatim from ggml's `ggml-common.h` (MIT licensed)
#![allow(clippy::all)]

"""


def resolve_size(token: str, defines: dict[str, int]) -> int:
    token = token.strip()
    if token.isdigit():
        return int(token)
    if token in defines:
        return defines[token]
    raise SystemExit(f"cannot resolve table size {token!r}")


def parse_defines(text: str) -> dict[str, int]:
    defines: dict[str, int] = {}
    for match in re.finditer(r"^#define\s+(\w+)\s+(\d+)\s*$", text, re.MULTILINE):
        defines[match.group(1)] = int(match.group(2))
    return defines


def collect_tables(text: str) -> dict[str, tuple[str, list[str]]]:
    defines = parse_defines(text)
    found: dict[str, tuple[str, list[str]]] = {}
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        match = BEGIN.search(lines[index])
        # Skip the `#define GGML_TABLE_BEGIN(...)` macro definitions themselves.
        if not match or lines[index].lstrip().startswith("#"):
            index += 1
            continue
        c_type, name, size_token = match.groups()
        size = resolve_size(size_token, defines)
        values: list[str] = []
        index += 1
        while index < len(lines) and END not in lines[index]:
            values.extend(re.findall(r"[-+]?0x[0-9a-fA-F]+|[-+]?\d+", lines[index]))
            index += 1
        if index >= len(lines):
            raise SystemExit(f"unterminated table {name}")
        if len(values) != size:
            raise SystemExit(
                f"table {name}: expected {size} values, parsed {len(values)}"
            )
        if name in TABLES:
            found[name] = (c_type, values)
        index += 1
    missing = set(TABLES) - set(found)
    if missing:
        raise SystemExit(f"missing tables in ggml-common.h: {sorted(missing)}")
    return found


def normalise(value: str, rust_type: str) -> str:
    if rust_type == "i8":
        return str(int(value, 0))
    return f"0x{int(value, 0):x}"


def render() -> str:
    text = SOURCE.read_text(encoding="utf-8")
    tables = collect_tables(text)
    out = [HEADER]
    for c_name, (rust_name, rust_type) in TABLES.items():
        _, values = tables[c_name]
        out.append(
            f"/// `{c_name}` from ggml-common.h ({len(values)} entries).\n"
        )
        out.append(f"pub const {rust_name}: [{rust_type}; {len(values)}] = [\n")
        width = 6 if rust_type == "i8" else 4
        for start in range(0, len(values), 8):
            chunk = values[start : start + 8]
            rendered = ", ".join(
                normalise(value, rust_type).rjust(width) for value in chunk
            )
            out.append(f"    {rendered},\n")
        out.append("];\n\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated file is up to date instead of writing it",
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"{TARGET} is stale; rerun scripts/gen_iq_tables.py", file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
